--liquibase formatted sql

--changeset agalkin:1
CREATE  TABLE  IF NOT EXISTS notification-tasks  (
    id  BIGINT GENERATED BY DEFAULT AS IDENTIFY PRIMARY KEY,
    user_id BIG INT NOT NULL,
    message TEXT NOT NULL,
    notification-date-time TIMESTAMP NOT NULL
);
